/*
 * generated by Xtext 2.16.0
 */
package hu.blackbelt.judo.meta.jql.validation

import hu.blackbelt.judo.meta.jql.jqldsl.Expression
import org.eclipse.emf.common.util.URI
import org.eclipse.emf.ecore.EObject
import org.eclipse.xtext.validation.Check

/**
 * This class contains custom validation rules. 
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class JqlDslValidator extends AbstractJqlDslValidator {

	@Check
	def checkSomething(Expression expression) {

	}

	def currentElem(EObject grammarElement) {
		return grammarElement.eResource.resourceSet.getResource(URI.createURI("self_synthetic"), true).contents.get(0)
	}

}
