/*
 * generated by Xtext 2.16.0
 */
package hu.blackbelt.judo.meta.psm.jql


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class JqlDslRuntimeModule extends AbstractJqlDslRuntimeModule {
}
