/*
 * generated by Xtext 2.16.0
 */
package hu.blackbelt.judo.jql.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class JqlDslWebModule extends AbstractJqlDslWebModule {
}
