/**
 * generated by Xtext 2.18.0
 */
package hu.blackbelt.judo.meta.jql.ide;

import hu.blackbelt.judo.meta.jql.ide.AbstractJqlDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class JqlDslIdeModule extends AbstractJqlDslIdeModule {
}
