/*
 * generated by Xtext 2.18.0
 */
package hu.blackbelt.judo.meta.jql.ui;

import com.google.inject.Injector;
import hu.blackbelt.judo.meta.jql.ui.internal.JqlUiModelActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class JqlDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(JqlUiModelActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		JqlUiModelActivator activator = JqlUiModelActivator.getInstance();
		return activator != null ? activator.getInjector(JqlUiModelActivator.HU_BLACKBELT_JUDO_META_JQL_JQLDSL) : null;
	}

}
