/*
 * generated by Xtext 2.16.0
 */
package hu.blackbelt.judo.meta.psm.jql.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class JqlDslScopeProvider extends AbstractJqlDslScopeProvider {

}
