/*
 * generated by Xtext 2.16.0
 */
package hu.blackbelt.judo.meta.jql


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class JqlDslStandaloneSetup extends JqlDslStandaloneSetupGenerated {

    def static void doSetup() {
        new JqlDslStandaloneSetup().createInjectorAndDoEMFRegistration()
    }
}
